FROM rust:latest AS builder
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /target/release/server /usr/local/bin/server
CMD ["/usr/local/bin/server"]

